const reduxConst = {
    ADD_ITEM_TO_ORDER: 'ADD_ITEM_TO_ORDER',
    ADD_NEW_ACCOUNT_TO_STORE: 'ADD_NEW_ACCOUNT_TO_STORE',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM_FROM_ORDER: 'REMOVE_ITEM_FROM_ORDER',
    SELECT_MENU_TO_EDIT: 'SELECT_MENU_TO_EDIT',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USERS_MENU_ACCOUNTS: 'SET_USERS_MENU_ACCOUNTS',
    TOGGLE_ORDER_HIDDEN: 'TOGGLE_ORDER_HIDDEN',
}

export default reduxConst