const reduxConst = {
    ADD_ITEM_TO_ORDER: 'ADD_ITEM_TO_ORDER',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM_FROM_ORDER: 'REMOVE_ITEM_FROM_ORDER',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    TOGGLE_ORDER_HIDDEN: 'TOGGLE_ORDER_HIDDEN',
}

export default reduxConst